create table hist_loan(
id int AUTO_INCREMENT,
End_of_Period DATE,
Loan_Number VARCHAR(10),
Region VARCHAR(50),
Country_Code VARCHAR(10),
Country VARCHAR(50),
Borrower VARCHAR(50),
Guarantor_Country_Code VARCHAR(10),
Guarantor VARCHAR(50),
Loan_Type VARCHAR(50),
Loan_Status VARCHAR(50),
Interest_Rate DECIMAL(6, 4),
Currency_of_Commitment VARCHAR(50),
Project_ID VARCHAR(10),
Project_Name VARCHAR(50),
Original_Principal_Amount DECIMAL(14, 2),
Cancelled_Amount DECIMAL(14, 2),
Undisbursed_Amount DECIMAL(14, 2),
Disbursed_Amount DECIMAL(14, 2),
Repaid_to_IBRD DECIMAL(14, 2),
Due_to_IBRD DECIMAL(14, 2),
Exchange_Adjustment DECIMAL(14, 2),
Borrowers_Obligation DECIMAL(14, 2),
Sold_3rd_Party DECIMAL(14, 2),
Repaid_3rd_Party DECIMAL(14, 2),
Due_3rd_Party DECIMAL(14, 2),
Loans_Held DECIMAL(14, 2),
First_Repayment_Date DATE,
Last_Repayment_Date DATE,
Agreement_Signing_Date DATE,
Board_Approval_Date DATE,
Effective_Date DATE,
Closed_Date DATE,
Last_Disbursement_Date DATE,
PRIMARY KEY (id)
);

LOAD DATA LOCAL INFILE '/home/ruch/Downloads/IBRD_Statement_Of_Loans_-_Historical_Data.csv' INTO TABLE hist_loan FIELDS TERMINATED BY "," ENCLOSED BY '"' LINES TERMINATED BY "\n" IGNORE 1 ROWS (@c1,@c2,@c3,@c4,@c5,@c6,@c7,@c8,@c9,@c10,@c11,@c12,@c13,@c14,@c15,@c16,@c17,@c18,@c19,@c20,@c21,@c22,@c23,@c24,@c25,@c26,@c27,@c28,@c29,@c30,@c31,@c32,@c33) SET
End_of_Period = NULLIF(@c1,''),
Loan_Number = NULLIF(@c2,''),
Region = NULLIF(@c3,''),
Country_Code = NULLIF(@c4,''),
Country = NULLIF(@c5,''),
Borrower = NULLIF(@c6,''),
Guarantor_Country_Code = NULLIF(@c7,''),
Guarantor = NULLIF(@c8,''),
Loan_Type = NULLIF(@c9,''),
Loan_Status = NULLIF(@c10,''),
Interest_Rate = NULLIF(@c11,''),
Currency_of_Commitment = NULLIF(@c12,''),
Project_ID = NULLIF(@c13,''),
Project_Name = NULLIF(@c14,''),
Original_Principal_Amount =NULLIF(@c15,''),
Cancelled_Amount = NULLIF(@c16,''),
Undisbursed_Amount = NULLIF(@c17,''),
Disbursed_Amount = NULLIF(@c18,''),
Repaid_to_IBRD = NULLIF(@c19,''),
Due_to_IBRD = NULLIF(@c20,''),
Exchange_Adjustment = NULLIF(@c21,''),
Borrowers_Obligation = NULLIF(@c22,''),
Sold_3rd_Party = NULLIF(@c23,''),
Repaid_3rd_Party = NULLIF(@c24,''),
Due_3rd_Party = NULLIF(@c25,''),
Loans_Held = NULLIF(@c26,''),
First_Repayment_Date =  NULLIF(@c27,''),
Last_Repayment_Date =NULLIF(@c28,''),
Agreement_Signing_Date=NULLIF(@c29,''),
Board_Approval_Date=NULLIF(@c30,''),
Effective_Date=NULLIF(@c31,''),
Closed_Date=NULLIF(@c32,''),
Last_Disbursement_Date =NULLIF(@c33,''),
End_of_Period=STR_TO_DATE(@c1,'%m/%d/%Y'),
First_Repayment_Date=STR_TO_DATE(@c27,'%m/%d/%Y'),
Last_Repayment_Date=STR_TO_DATE(@c28,'%m/%d/%Y'),
Agreement_Signing_Date=STR_TO_DATE(@c29,'%m/%d/%Y'),
Board_Approval_Date=STR_TO_DATE(@c30,'%m/%d/%Y'),
Effective_Date=STR_TO_DATE(@31,'%m/%d/%Y'),
Closed_Date=STR_TO_DATE(@c32,'%m/%d/%Y'),
Last_Disbursement_Date=STR_TO_DATE(@c33,'%m/%d/%Y');


